import type { SkillDef } from './skills.js';

export function skillsText(defs: SkillDef[]): string {
  return ['🎬 skills registradas:', ...defs.map((d) => `• ${d.command} — ${d.description}\n  ex.: ${d.example}`)].join('\n');
}

export function helpText(defs: SkillDef[], dests: string[]): string {
  return [
    '🤖 inemaccvbot — DUAS filas de jobs (mesmo daemon mkivideos, dois bancos/dashboards separados)',
    '  🎬 vídeo (mkivideos.service) — explicativo, curso, demo — render, ~15min por job',
    '  📝 texto (mkitexto.service) — transcrever, dublar — via inemavox, minutos por job',
    'Separadas pra um pedido de texto não esperar horas atrás de um render — cada fila tem seu',
    'próprio ETA, e uma fila fora do ar nunca bloqueia a outra.',
    '',
    'Mande instruções em texto — uma instrução por linha = um job:',
    '  <skill>: <assunto ou link> [| 9:16] [| pesquisa] [| narracao] [| transcrever] [| livesN] [| modulo X] [| curso X]',
    '',
    'Exemplos:',
    ...defs.map((d) => `  ${d.example}`),
    '  explicativo: Computação quântica | pesquisa | lives2',
    '  explicativo: O que é RAG | narracao',
    '  explicativo: https://instagram.com/reel/XYZ | transcrever',
    '',
    'Campos (qualquer ordem):',
    '  9:16 ou vertical — formato Shorts/Reels (default 16:9)',
    '  pesquisa — o agente que gera o vídeo pesquisa o assunto na web antes de escrever o roteiro',
    '  narracao ou texto — além do vídeo, manda aqui a narração completa em texto (mensagem se couber, senão como arquivo)',
    '  transcrever ou transcricao — CAMPO de um job de VÍDEO: o agente baixa o áudio do link de origem e transcreve localmente (inemavox, Whisper local) ANTES de escrever o roteiro, usando essa transcrição como base do vídeo — pedido é enfileirado, não confirmado: se a transcrição falhar, o job falha e aparece em /status',
    `  livesN — move o resultado pronto para yt-pub-livesN/imports/videos (válidos: ${dests.join(', ') || 'nenhum'})`,
    '',
    'Atenção: "transcrever" existe de DUAS formas diferentes — não confundir:',
    '  • CAMPO num job de vídeo (acima) — ex.: "explicativo: <link> | transcrever" — GERA VÍDEO, usando o áudio de origem como base.',
    '  • SKILL própria, fila de texto — "transcrever: <link>" — NÃO gera vídeo, devolve só o TEXTO falado.',
    '',
    'Texto livre também funciona (o bot interpreta), mas SÓ com as skills registradas — nada é criado fora delas.',
    '',
    'Também dá pra mandar um arquivo (ex.: .md) anexado, com uma legenda dizendo o que fazer com ele',
    '(ex.: "explicativo: resumo desse documento") — o bot baixa o arquivo e passa pro agente de render',
    'como fonte do vídeo. Sem legenda, o bot só pergunta o que fazer, sem enfileirar nada.',
    '',
    'reel — vídeo 9:16 empilhado a partir de um avatar HeyGen (skill reel-edita-inema). Duas formas',
    'de mandar o avatar (o input é o MP4, não um assunto/link):',
    '  • CAMINHO (forma principal) — ex.: "reel: /home/.../avatar.mp4 | lives3" — avatares costumam',
    '    passar de 20 MB, acima do limite de download do bot, então o caminho é a via confiável.',
    '  • ANEXO — só funciona <20 MB — anexe o .mp4 com a legenda "reel" (ou "reel | lives3 | mover").',
    'Campos do reel: livesN COPIA o resultado pra lá por padrão (mantém o original em',
    '~/projetos/output/<slug>/); "| mover" MOVE em vez de copiar; "| visuais" usa o Modo 3 (visuais)',
    'em vez do explicador (Modo 2, default). Sem destino, o reel fica só em ~/projetos/output/.',
    '',
    'Também dá pra perguntar em linguagem natural sobre o andamento do serviço, ou sobre o que o bot',
    'sabe fazer — o bot responde com base nas duas filas, no que já foi feito e nas skills registradas,',
    'sem criar nenhum job novo. Exemplos:',
    '  terminou?',
    '  quanto falta pro V12?',
    '  você já moveu o vídeo pro lives3?',
    '  você consegue transcrever o áudio de um reel?',
    '',
    'IDs de job aparecem PREFIXADOS — V#12 é da fila de vídeo, T#7 é da fila de texto (ids são',
    'por-fila, então um V#7 e um T#7 podem existir ao mesmo tempo e são jobs diferentes). Use o',
    'prefixo (com ou sem "#", maiúsculo ou minúsculo — V7, v#7, V#7 valem) em /status, /cancelar e',
    '/enviar. Sem prefixo, só funciona se o número for único entre os jobs rastreados deste chat —',
    'caso contrário o bot pergunta qual fila em vez de adivinhar.',
    '',
    'Comandos:',
    '  /fila — running + queued com posição, das DUAS filas',
    '  /status [id] — detalhe do job pelo id (V#/T#); sem id: visão geral + stats das DUAS filas',
    '  /cancelar <id> — cancela job na fila (V#/T#)',
    '  /enviar <id> — recebe o arquivo aqui (≤50 MB; acima, só o caminho)',
    '  /skills — o que o bot sabe fazer',
    '  /help — esta ajuda',
  ].join('\n');
}
