import type { SkillDef } from './skills.js';

export function skillsText(defs: SkillDef[]): string {
  return ['🎬 skills registradas:', ...defs.map((d) => `• ${d.command} — ${d.description}\n  ex.: ${d.example}`)].join('\n');
}

export function helpText(defs: SkillDef[], dests: string[]): string {
  return [
    '🤖 inemaccvbot — DUAS filas (mesmo daemon mkivideos, bancos separados)',
    '  🎬 fila de vídeo — explicativo, curso, demo, reel (render, ~15-30min)',
    '  📝 fila de texto — transcrever, dublar (via inemavox, minutos)',
    'Uma fila fora do ar nunca bloqueia a outra.',
    '',
    'Mande instruções — uma instrução por linha = um job:',
    '  <skill>: <assunto/link> [| campos...]',
    '',
    'Exemplos:',
    ...defs.map((d) => `  ${d.example}`),
    '  explicativo: Computação quântica | pesquisa | narracao | lives2',
    '',
    'Campos (qualquer ordem):',
    '  9:16 / vertical — Shorts/Reels (default 16:9)',
    '  pesquisa — pesquisa o assunto na web antes do roteiro',
    '  narracao / texto — manda a narração em texto além do vídeo',
    '  transcrever — CAMPO de job de vídeo: usa o áudio de origem como base do roteiro',
    `  livesN — move o resultado pra yt-pub-livesN/imports/videos (válidos: ${dests.join(', ') || 'nenhum'})`,
    '',
    '⚠️ não confundir "transcrever" (dois sentidos): CAMPO ("explicativo: <link> | transcrever") GERA vídeo com',
    'base no áudio; SKILL ("transcrever: <link>") devolve só o TEXTO, sem vídeo.',
    '',
    'Texto livre também funciona (o bot interpreta), só com skills registradas.',
    'Arquivo anexado (.md, etc.) com legenda vira fonte do vídeo. Sem legenda, o bot pergunta.',
    '',
    'REEL (9:16 de um avatar HeyGen, skill reel-edita-inema). O input é o MP4:',
    '  /reel /home/.../avatar.mp4 quero modo capa de impacto  — comando dedicado (recomendado)',
    '  CAMINHO é a via confiável (avatar passa de 20 MB, limite de anexo do bot). ANEXO só <20 MB.',
    '  Campos: livesN COPIA (original fica em ~/projetos/output/reels/); | mover MOVE; | visuais usa',
    '  Modo 3; | capa/impacto usa Modo 4. Pedir "imagem/ilustrativa" solto já ativa visuais.',
    '  PASTA: /reel /caminho/pasta/ [descrição] → UM reel por vídeo (.mp4/.mov/.m4v/.webm, sem recursão),',
    '  mesmas flags pra todos; responde "N reels na fila: V#..".',
    'reelinematds — reel estilo INEMATDS de um bruto vertical: /reelinematds /home/.../bruto.mp4 [desc].',
    '',
    'Pergunta em linguagem natural também funciona, sem criar job: "terminou?", "quanto falta pro V12?".',
    '',
    'IDs PREFIXADOS — V#12 (vídeo), T#7 (texto); um V#7 e um T#7 coexistem. Prefixo vale em',
    '/status, /cancelar, /enviar. Sem prefixo, só se o número for único.',
    '',
    'Comandos:',
    '  /fila — running + queued das DUAS filas',
    '  /status [id] — detalhe do job; sem id: stats gerais',
    '  /cancelar <id> — cancela job na fila',
    '  /enviar <id> — recebe o arquivo (≤50 MB pelo Telegram; acima, link de download + caminho)',
    '  /reel <caminho|pasta> [descrição] — atalho pra skill reel',
    '  /promoclub <assunto> [| publicos=a,b] [| versao=N] — pipeline INEMA.club: gera os textos',
    '    por público (11 canais lives21-31), você renderiza no HeyGen, e o bot baixa + enfileira',
    '    os reels sozinho. /promoclub status [assunto] · /promoclub baixar <assunto>',
    '  /skills — o que o bot sabe fazer',
    '  /help — esta ajuda',
  ].join('\n');
}
